image: ruby:2.1

pages:
  stage: deploy
  environment: production
  script:
  - gem install redcarpet
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

develop:
  stage: deploy
  environment: develop
  script:
  - gem install redcarpet jekyll dpl
  - jekyll build -d public
  - echo $CI_PROJECT_DIR
  - echo $TRAVIS_BUILD_DIR
  - dpl --provider=surge --project=public --domain=develop.www.singuerinc.com.surge.sh
  only:
  - develop