image: mwallasch/docker-ruby-node

pages:
  stage: deploy
  environment: production
  script:
  - gem install redcarpet
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

develop:
  stage: deploy
  environment: develop
  script:
  - gem install redcarpet jekyll
  - jekyll build -d $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_DIR
  - npm install -g surge
  - surge -p $TRAVIS_BUILD_DIR -d develop.www.singuerinc.com.surge.sh
  artifacts:
    paths:
    - public
  only:
  - develop