image: ruby:2.3

pages:
  script:
  - gem install redcarpet
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

staging:
  script:
  - gem install redcarpet jekyll dpl
  - jekyll build -d public
  - dpl --provider=firebase --token=1/2GJtCAQ8E88zQHgZl5cysXC3YqaIKsVVpOlpkM0U2Lg --project=test-www-a3401
  artifacts:
    paths:
    - public
  only:
  - develop