stages:
- build
- test
- deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/singuerinc-works/com.singuerinc.www:$CI_BUILD_TAG
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/singuerinc-works/com.singuerinc.www:latest

test:build:
  image: jekyll/jekyll:3.2.1
  environment: test
  stage: build
  artifacts:
    expire_in: 20 minutes
    untracked: true
  script:
  - apk add --update nodejs
  - npm install
  - npm run build
  - jekyll build -d $TRAVIS_BUILD_DIR
  only:
  - branches
  except:
  - master

test:test:urls:
  image: jekyll/jekyll:3.2.1
  environment: test
  stage: test
  script:
  - htmlproofer $TRAVIS_BUILD_DIR --log-level debug
  only:
  - branches
  except:
  - master

test:test:functional:
  image: singuerinc/docker_casperjs
  environment: test
  stage: test
  script:
  - echo "0.0.0.0 jekyll" >> /etc/hosts
  - cd $CI_PROJECT_DIR/public
  - python -m SimpleHTTPServer 4000 &
  - casperjs test $CI_PROJECT_DIR/_tests/index.js
  only:
  - branches
  except:
  - master

test:deploy:
  image: mhart/alpine-node:6
  environment: test
  stage: deploy
  script:
  - npm install -g surge
  - surge -p $TRAVIS_BUILD_DIR -d test.www.singuerinc.com.surge.sh
  only:
  - branches
  except:
  - master

staging:build:
  image: jekyll/jekyll:3.2.1
  environment: staging
  stage: build
  artifacts:
    expire_in: 20 minutes
    untracked: true
  script:
  - apk add --update nodejs
  - npm install
  - npm run build
  - jekyll build -d $TRAVIS_BUILD_DIR
  only:
  - master

staging:test:urls:
  image: jekyll/jekyll:3.2.1
  environment: staging
  stage: test
  script:
  - htmlproofer $TRAVIS_BUILD_DIR --log-level debug
  only:
  - master

staging:test:functional:
  image: singuerinc/docker_casperjs
  environment: staging
  stage: test
  script:
  - echo "0.0.0.0 jekyll" >> /etc/hosts
  - cd $CI_PROJECT_DIR/public
  - python -m SimpleHTTPServer 4000 &
  - casperjs test $CI_PROJECT_DIR/_tests/index.js
  only:
  - master

staging:deploy:
  image: mhart/alpine-node:6
  environment: staging
  stage: deploy
  script:
  - npm install -g surge
  - surge -p $TRAVIS_BUILD_DIR -d staging.www.singuerinc.com.surge.sh
  only:
  - master

pages:build:
  image: jekyll/jekyll:3.2.1
  environment: production
  stage: build
  artifacts:
    expire_in: 20 minutes
    untracked: true
  script:
  - apk add --update nodejs
  - npm install
  - npm run build
  - jekyll build -d $TRAVIS_BUILD_DIR
  only:
  - tags

pages:test:urls:
  image: jekyll/jekyll:3.2.1
  environment: production
  stage: test
  script:
  - htmlproofer $TRAVIS_BUILD_DIR --log-level debug
  only:
  - tags

pages:test:functional:
  image: singuerinc/docker_casperjs
  environment: production
  stage: test
  script:
  - echo "0.0.0.0 jekyll" >> /etc/hosts
  - cd $CI_PROJECT_DIR/public
  - python -m SimpleHTTPServer 4000 &
  - casperjs test $CI_PROJECT_DIR/_tests/index.js
  only:
  - tags

pages:
  image: ruby:2.1
  environment: production
  stage: deploy
  script:
  - gem install redcarpet jekyll jekyll-sitemap
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - tags

pages:push-docker-images:
  image: docker:git
  services:
  - docker:dind
  environment: production
  stage: deploy
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - tags
