image: mwallasch/docker-ruby-node

staging:
  stage: deploy
  script:
  - gem install redcarpet jekyll
  - jekyll build -d $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_DIR
  - npm install -g surge
  - surge -p $TRAVIS_BUILD_DIR -d develop.www.singuerinc.com.surge.sh
  only:
  - master

pages:
  stage: deploy
  script:
  - gem install redcarpet
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - tags
