image: ruby:2.1

pages:
  stage: deploy
  environment: production
  script:
  - gem install redcarpet
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

develop:
  stage: deploy
  environment: develop
  script:
  - gem install redcarpet jekyll dpl
  - jekyll build -d public
  - dpl --provider=surge --project=public --domain=www-singuerinc-com--develop.surge.sh
  artifacts:
    paths:
    - public
  only:
  - develop