image: mwallasch/docker-ruby-node

pages:
  script:
  - gem install redcarpet
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

staging:
  script:
  - gem install redcarpet jekyll
  - jekyll build -d public
  - dpl --provider=heroku --api-key="c382ae05-0aec-4e7c-9958-5f9f2cde7043" --app="www-singuerinc"
  artifacts:
    paths:
    - public
  only:
  - develop