stages:
- build
- test
- deploy

test_build:
  image: ruby:2.1
  environment: test
  stage: build
  script:
  - gem install redcarpet jekyll jekyll-sitemap
  - jekyll build -d $TRAVIS_BUILD_DIR
  cache:
    paths:
      - $TRAVIS_BUILD_DIR
  only:
  - branches
  except:
  - master

test_test:
  image: ruby:2.1
  environment: test
  stage: test
  script:
  - gem install redcarpet jekyll jekyll-sitemap html-proofer
  - jekyll build -d $TRAVIS_BUILD_DIR
  - htmlproofer $TRAVIS_BUILD_DIR --disable-external
  only:
  - branches
  except:
  - master

test:
  image: mwallasch/docker-ruby-node
  environment: test
  stage: deploy
  script:
  - gem install redcarpet jekyll jekyll-sitemap
  - jekyll build -d $TRAVIS_BUILD_DIR
  - npm install -g surge
  - surge -p $TRAVIS_BUILD_DIR -d test.www.singuerinc.com.surge.sh
  only:
  - branches
  except:
  - master

staging:
  image: mwallasch/docker-ruby-node
  environment: staging
  stage: deploy
  script:
  - gem install redcarpet jekyll jekyll-sitemap
  - jekyll build -d $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_DIR
  - npm install -g surge
  - surge -p $TRAVIS_BUILD_DIR -d staging.www.singuerinc.com.surge.sh
  only:
  - master

pages:
  image: ruby:2.1
  environment: production
  stage: deploy
  script:
  - gem install redcarpet jekyll jekyll-sitemap
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - tags
