stages:
- build
- test
- deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/singuerinc-works/com.singuerinc.www:$CI_BUILD_TAG
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/singuerinc-works/com.singuerinc.www:latest

.build: &build-definition
  image: jekyll/jekyll:3.2.1
  stage: build
  cache:
    paths:
    - node_modules/
  script:
  - apk add --update nodejs
  - npm i -g yarn
  - yarn
  - yarn run build:js
  - JEKYLL_ENV=test yarn run build -- --config _config.yml,_config-test.yml
  - yarn run build:css
  - rm $CI_PROJECT_DIR/public/robots.txt
  - 'printf "User-agent: *\nDisallow: /" > $CI_PROJECT_DIR/public/robots.txt'

.test-functional: &test-functional-definition
  image: singuerinc/docker_casperjs
  stage: test
  script:
  - export SITE_URL="http://$TEST_DOMAIN"
  - echo "0.0.0.0 jekyll" >> /etc/hosts
  - cd $CI_PROJECT_DIR/public
  - python -m SimpleHTTPServer 4000 &
  - casperjs test $CI_PROJECT_DIR/_tests/index.js

.test-unit: &test-unit-definition
  image: mhart/alpine-node:7.5.0
  stage: test
  script:
  - npm i -g yarn
  - yarn
  - yarn run test
  - yarn run report

.deploy: &deploy-definition
  image: mhart/alpine-node:7.5.0
  stage: deploy
  variables:
    GIT_STRATEGY: none

test:build:
  <<: *build-definition
  environment: test
  artifacts:
    paths:
    - public
    expire_in: 45 minutes
  only:
  - branches
  except:
  - master

test:unit_test:
  <<: *test-unit-definition
  environment: test
  only:
  - branches
  except:
  - master

test:functional_test:
  <<: *test-functional-definition
  environment: test
  only:
  - branches
  except:
  - master

test:deploy:
  <<: *deploy-definition
  environment: test
  script:
  - npm install -g surge
  - rm $CI_PROJECT_DIR/public/CNAME
  - printf "$TEST_DOMAIN" > $CI_PROJECT_DIR/public/CNAME
  - surge -p $CI_PROJECT_DIR/public
  only:
  - branches
  except:
  - master

staging:build:
  <<: *build-definition
  environment: staging
  artifacts:
    paths:
    - public
    expire_in: 45 minutes
  script:
  - apk add --update nodejs
  - npm i -g yarn
  - yarn
  - yarn run build:js -- -p
  - JEKYLL_ENV=staging yarn run build -- --config _config.yml,_config-staging.yml
  - yarn run build:css
  - rm $CI_PROJECT_DIR/public/robots.txt
  - 'printf "User-agent: *\nDisallow: /" > $CI_PROJECT_DIR/public/robots.txt'
  only:
  - master

staging:functional_test:
  <<: *test-functional-definition
  environment: staging
  script:
  - export SITE_URL="http://$STAGING_DOMAIN"
  - echo "0.0.0.0 jekyll" >> /etc/hosts
  - cd $CI_PROJECT_DIR/public
  - python -m SimpleHTTPServer 4000 &
  - casperjs test $CI_PROJECT_DIR/_tests/index.js
  only:
  - master

staging:unit_test:
  <<: *test-unit-definition
  environment: staging
  only:
  - master

staging:deploy:
  <<: *deploy-definition
  environment: staging
  script:
  - npm install -g surge
  - rm $CI_PROJECT_DIR/public/CNAME
  - printf "$STAGING_DOMAIN" > $CI_PROJECT_DIR/public/CNAME
  - surge -p $CI_PROJECT_DIR/public
  only:
  - master

pages:build:
  <<: *build-definition
  environment: production
  artifacts:
    paths:
    - public
  script:
  - apk add --update nodejs
  - npm i -g yarn
  - yarn
  - yarn run build:js -- -p
  - JEKYLL_ENV=test yarn run build
  - yarn run build:css
  only:
  - tags

pages:functional_test:
  <<: *test-functional-definition
  environment: production
  script:
  - export SITE_URL="https://$PROD_DOMAIN"
  - echo "0.0.0.0 jekyll" >> /etc/hosts
  - cd $CI_PROJECT_DIR/public
  - python -m SimpleHTTPServer 4000 &
  - casperjs test $CI_PROJECT_DIR/_tests/index.js
  only:
  - tags

pages:unit_test:
  <<: *test-unit-definition
  environment: production
  only:
  - tags

pages:
  image: ruby:2.1
  environment: production
  stage: deploy
  script:
  - gem install redcarpet jekyll jekyll-sitemap
  - JEKYLL_ENV=production jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - tags

pages:push-docker-images:
  image: docker:git
  services:
  - docker:dind
  environment: production
  stage: deploy
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - tags
