image: ruby:2.1

pages:
  stage: deploy
  environment: production
  script:
  - gem install redcarpet
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

develop:
  stage: deploy
  environment: develop
  script:
  - gem install redcarpet jekyll dpl
  - jekyll build -d public
  - echo $TRAVIS_BUILD_DIR
  - dpl --skip_cleanup --provider=surge --domain=develop-www-singuerinc-com.surge.sh
  artifacts:
    paths:
    - public
  only:
  - develop