image: mwallasch/docker-ruby-node

test:
  environment: test
  stage: deploy
  script:
  - gem install redcarpet jekyll jekyll-sitemap
  - jekyll build -d $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_DIR
  - npm install -g surge
  - surge -p $TRAVIS_BUILD_DIR -d test.www.singuerinc.com.surge.sh
  only:
  - branches
  except:
  - master

staging:
  environment: staging
  stage: deploy
  script:
  - gem install redcarpet jekyll jekyll-sitemap
  - jekyll build -d $TRAVIS_BUILD_DIR
  - echo $TRAVIS_BUILD_DIR
  - npm install -g surge
  - surge -p $TRAVIS_BUILD_DIR -d staging.www.singuerinc.com.surge.sh
  only:
  - master

pages:
  environment: production
  stage: deploy
  script:
  - gem install redcarpet jekyll jekyll-sitemap
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - tags
