markdown:         redcarpet
highlighter:      pygments

permalink:        none

title:            '@singuerinc'
tagline:          ''
description:      ''
url:              https://www.singuerinc.com

author:
  name:           'Nahuel Scotti'
  url:            https://twitter.com/singuerinc

version:          2.0.0

github:
  repo:           https://github.com/singuerinc/

destination:      public

markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']

exclude: [Dockerfile, docker-compose.yml, README.md, CHANGELOG, gulpfile.js, node_modules, webpack.config.js, package.json, app.js]

encoding: utf8

gems:
  - html-proofer
  - jekyll-sitemap
