markdown:         redcarpet
highlighter:      pygments

permalink:        pretty

title:            '@singuerinc'
tagline:          ''
description:      ''
url:              https://singuerinc.gitlab.io/www.singuerinc.com/

author:
  name:           'Nahuel Scotti'
  url:            https://twitter.com/singuerinc

version:          2.0.0

github:
  repo:           https://github.com/singuerinc/
