version: "2"
services:
  jekyll:
    image: jekyll/jekyll
    command: jekyll s
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ./:/srv/jekyll
  webpack:
    build:
      context: .
      dockerfile: Dockerfile-webpack
    command: webpack --progress --watch
    volumes:
      - ./:/usr/src/app
