version: "2"
services:
  jekyll:
    image: jekyll/jekyll:3.2.1
    command: jekyll s --config _config.yml,_config-dev.yml
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ./:/srv/jekyll
    stdin_open: true
    tty: true

  webpack:
    image: singuerinc/www-webpack
    build:
      context: .
      dockerfile: Dockerfile-webpack
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
    command: yarn run build:js
    volumes:
      - ./:/usr/src/app
    stdin_open: true
    tty: true

  tests-links:
    image: jekyll/jekyll:3.2.1
    command: htmlproofer /srv/jekyll/public --log-level debug
    volumes_from:
      - jekyll
    depends_on:
      - jekyll
