FROM mwallasch/docker-ruby-node
VOLUME ["/src/app"]
RUN mkdir -p /src
WORKDIR /src
RUN npm install phantomjs-prebuilt casperjs
RUN ln -s /src/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /usr/local/bin/
WORKDIR /src/app
CMD ["node_modules/casperjs/bin/casperjs", "test", "test.js"]
